# Generated by Django 5.2.12 on 2026-08-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
