# Generated by Django 5.2.12 on 2026-08-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='extra_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('headline_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
