# Generated by Django 5.2.12 on 2026-08-08 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0003_extra_info_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_info',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='zevera.category'),
        ),
    ]
