# Generated by Django 5.2.12 on 2026-08-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0005_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
