# Generated by Django 5.2.12 on 2026-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0007_reviews_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_score',
            field=models.IntegerField(null=True),
        ),
    ]
