# Generated by Django 5.2.12 on 2026-08-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0008_reviews_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_score',
        ),
    ]
