# Generated by Django 5.2.12 on 2026-08-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0009_remove_reviews_review_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
