# Generated by Django 5.2.12 on 2026-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0012_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
