# Generated by Django 5.2.12 on 2026-08-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0014_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(default=6, max_length=5, null=True),
        ),
    ]
