# Generated by Django 5.2.12 on 2026-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0021_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dynamic_price',
            field=models.FloatField(null=True),
        ),
    ]
