# Generated by Django 5.2.12 on 2026-09-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zevera', '0022_cart_dynamic_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
